from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

OUT = r"output/pdf/Proposta_Piloto_WhatsApp_Life_Engenharia.pdf"
NAVY=colors.HexColor("#123E6A"); CYAN=colors.HexColor("#00A9D6"); PALE=colors.HexColor("#EAF6FB")
MIST=colors.HexColor("#F4F7F9"); INK=colors.HexColor("#263B4D"); MUTED=colors.HexColor("#627487"); LINE=colors.HexColor("#D3E0E8")
s=getSampleStyleSheet()
s.add(ParagraphStyle(name="Kicker",parent=s["BodyText"],fontName="Helvetica-Bold",fontSize=10,leading=13,textColor=CYAN,alignment=TA_CENTER,spaceAfter=12))
s.add(ParagraphStyle(name="Cover",parent=s["Title"],fontName="Helvetica-Bold",fontSize=29,leading=34,textColor=NAVY,alignment=TA_CENTER,spaceAfter=14))
s.add(ParagraphStyle(name="Sub",parent=s["BodyText"],fontName="Helvetica",fontSize=13,leading=19,textColor=MUTED,alignment=TA_CENTER))
s.add(ParagraphStyle(name="H1",parent=s["Heading1"],fontName="Helvetica-Bold",fontSize=19,leading=23,textColor=NAVY,spaceAfter=9))
s.add(ParagraphStyle(name="H2",parent=s["Heading2"],fontName="Helvetica-Bold",fontSize=11.5,leading=15,textColor=NAVY,spaceBefore=9,spaceAfter=5))
s.add(ParagraphStyle(name="Body",parent=s["BodyText"],fontName="Helvetica",fontSize=9.4,leading=13.2,textColor=INK,spaceAfter=5))
s.add(ParagraphStyle(name="Cell",parent=s["BodyText"],fontName="Helvetica",fontSize=8.35,leading=11.2,textColor=INK))
s.add(ParagraphStyle(name="Header",parent=s["BodyText"],fontName="Helvetica-Bold",fontSize=8.25,leading=10.6,textColor=colors.white))
s.add(ParagraphStyle(name="Note",parent=s["BodyText"],fontName="Helvetica",fontSize=7.8,leading=10.4,textColor=MUTED))
s.add(ParagraphStyle(name="Callout",parent=s["BodyText"],fontName="Helvetica-Bold",fontSize=10,leading=14.5,textColor=NAVY,backColor=PALE,borderColor=CYAN,borderWidth=.7,borderPadding=8,borderRadius=4,spaceBefore=4,spaceAfter=9))
def P(t,style="Body"): return Paragraph(t,s[style])
def cell(v,header=False): return Paragraph(str(v),s["Header" if header else "Cell"])
def grid(rows,widths):
    data=[[cell(v,i==0) for v in row] for i,row in enumerate(rows)]
    t=Table(data,colWidths=widths,repeatRows=1,hAlign="LEFT")
    cmd=[("BACKGROUND",(0,0),(-1,0),NAVY),("GRID",(0,0),(-1,-1),.35,LINE),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]
    for r in range(2,len(data),2): cmd.append(("BACKGROUND",(0,r),(-1,r),MIST))
    t.setStyle(TableStyle(cmd)); return t
def band(title,body):
    t=Table([[P(title,"H2"),P(body)]],colWidths=[4.2*cm,13*cm],hAlign="LEFT")
    t.setStyle(TableStyle([("BACKGROUND",(0,0),(0,0),CYAN),("BACKGROUND",(1,0),(1,0),PALE),("TEXTCOLOR",(0,0),(0,0),colors.white),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),9),("RIGHTPADDING",(0,0),(-1,-1),9),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7),("BOX",(0,0),(-1,-1),.6,CYAN)])); return t
def footer(c,d):
    c.saveState(); c.setStrokeColor(CYAN); c.setLineWidth(2.5); c.line(d.leftMargin,A4[1]-1.05*cm,A4[0]-d.rightMargin,A4[1]-1.05*cm)
    c.setFillColor(NAVY); c.setFont("Helvetica-Bold",8); c.drawString(d.leftMargin,.7*cm,"LIFE ENGENHARIA | Piloto de atendimento via WhatsApp")
    c.setFillColor(MUTED); c.setFont("Helvetica",8); c.drawRightString(A4[0]-d.rightMargin,.7*cm,f"Página {d.page}"); c.restoreState()
doc=SimpleDocTemplate(OUT,pagesize=A4,leftMargin=1.55*cm,rightMargin=1.55*cm,topMargin=1.6*cm,bottomMargin=1.3*cm,title="Proposta Piloto WhatsApp Life Engenharia")
story=[]
# 1
story += [Spacer(1,2.5*cm),P("LIFE ENGENHARIA","Kicker"),P("Piloto de Atendimento\nvia WhatsApp","Cover"),P("Triagem comercial e técnica com decisão final da equipe humana","Sub"),Spacer(1,1.25*cm),band("OBJETIVO","Organizar a entrada de demandas, coletar informações essenciais, sugerir prioridade e encaminhar cada caso à equipe responsável."),Spacer(1,.45*cm),P("Proposta executiva","H1"),P("A solução usa o canal oficial do WhatsApp para estruturar o atendimento sem substituir a experiência e a responsabilidade da Life. O bot qualifica; Comercial e Assistência validam, decidem e retornam ao cliente."),Spacer(1,.45*cm),grid([["O piloto entrega","Resultado para a Life"],["Rota Comercial","Dados completos, resumo padronizado e oportunidade pronta para registro no Ploomes."],["Rota Técnica","Pré-triagem segura, prioridade sugerida P1-P4 e alerta imediato nos casos críticos."],["Roteamento humano","Encaminhamento por equipe, plantão, prioridade, região, horário e responsável de backup."]],[5*cm,12.2*cm]),Spacer(1,1*cm),P("Documento para aprovação de escopo, tecnologia, implantação e orçamento mensal.","Callout"),Spacer(1,2.1*cm),P("Versão inicial - setembro de 2026","Sub")]
# 2
story += [PageBreak(),P("1. Fluxo do piloto","H1"),P("O fluxo reproduz o manual operacional: entrada organizada, coleta mínima, resumo e transferência para uma pessoa."),band("FLUXO","Cliente -> consentimento -> Vendas ou Assistência -> perguntas específicas -> resumo -> fila responsável -> retorno humano."),P("Rotas e perguntas essenciais","H2"),grid([["Rota","O bot coleta","Saída"],["Comercial","Serviço, nome, empresa, cidade/unidade, telefone, e-mail, prazo, necessidade e anexos opcionais.","Resumo para Comercial e criação/atualização de oportunidade no Ploomes quando validado."],["Assistência técnica","Cliente/unidade, contrato, equipamento, modelo, sintoma, alarme, impacto, contingência, risco e evidências seguras.","Pré-triagem, prioridade sugerida e encaminhamento à fila técnica/plantão."]],[3*cm,8*cm,6.2*cm]),P("Prioridade técnica sugerida","H2"),grid([["Nível","Critério","Ação"],["P1 - Crítica","Risco a pessoas, sangue, medicamentos ou operação essencial; equipamento parado sem contingência.","Acionar plantão e exigir confirmação humana."],["P2 - Alta","Parada/falha relevante com contingência limitada.","Fila prioritária e retorno humano rápido."],["P3 - Normal","Falha parcial ou sem interrupção crítica.","Fila técnica regular."],["P4 - Programável","Preventiva, ajuste, dúvida ou visita programada.","Agendamento e confirmação humana."]],[3*cm,8*cm,6.2*cm]),P("Barreiras de segurança","H2"),P("O bot não emite diagnóstico, não orienta atividade com risco, não promete prazo e não altera estoque ou financeiro. O comando “falar com uma pessoa”, urgência, dúvida, silêncio ou falha de integração transferem o caso para a fila humana.","Callout")]
# 3
story += [PageBreak(),P("2. Tecnologia e implantação","H1"),P("Arquitetura enxuta para até 100 clientes, com evolução gradual e sem servidores complexos."),band("ARQUITETURA","Meta WhatsApp Cloud API -> API no Google Cloud Run -> PostgreSQL -> Ploomes/Fila humana. A IA interpreta texto livre e resume; não decide risco técnico."),P("Tecnologias e deploys","H2"),grid([["Camada","Tecnologia","Papel"],["Canal","Meta WhatsApp Cloud API","Número oficial, webhooks e envio de mensagens."],["Backend","Node.js, TypeScript e Fastify","Fluxos, protocolos, regras P1-P4 e integração com Ploomes."],["Deploy","Google Cloud Run - São Paulo","Contêiner HTTPS, escala automática e cobrança por uso."],["Dados","PostgreSQL gerenciado","Conversas, clientes, anexos, equipes, auditoria e protocolos."],["IA","OpenAI API - GPT-5 Mini","Classificação auxiliar, extração e resumo de texto."],["Segurança","Google Secret Manager","Chaves e credenciais fora do código."]],[2.6*cm,4.6*cm,10*cm]),P("Ambientes","H2"),grid([["Ambiente","Uso","Configuração inicial"],["Homologação","Testar fluxos, plantão, P1/P2 e Ploomes sem impactar clientes.","Cloud Run separado, número Meta de teste e base de teste."],["Produção","Atender o grupo piloto com rastreabilidade.","1 vCPU, 512 MB, mínimo 0, máximo 3 instâncias e banco de produção."]],[3.1*cm,7.2*cm,6.9*cm]),P("Plano de quatro semanas","H2"),grid([["Semana","Entrega"],["1","Aprovar perguntas, serviços, prioridades, responsáveis, horários e mensagens de segurança."],["2","Configurar canal, banco, fluxos, protocolo, filas humanas e contingência."],["3","Executar ao menos 20 testes: comercial, P1/P2, sem contrato, anexos, humano e falhas."],["4","Piloto controlado, acompanhamento diário e decisão de ampliar, corrigir ou pausar."]],[2*cm,15.2*cm])]
# 4
story += [PageBreak(),P("3. Investimento e aprovação","H1"),P("Estimativa para 100 clientes ativos, cerca de 2.000 mensagens automáticas/mês, sem campanhas de marketing, mídia ou CRM pago. Valores variam por consumo, câmbio, impostos e tabelas dos fornecedores."),grid([["Componente","Estimativa mensal","Premissa"],["PostgreSQL - produção","R$ 140","Banco gerenciado e backup."],["Homologação","R$ 0 a R$ 55","Teste gratuito ou ambiente estável separado."],["Google Cloud Run","R$ 0 a R$ 15","Baixo volume e cobrança por uso."],["OpenAI API","R$ 10 a R$ 30","Resumos e classificação com contexto controlado."],["Meta WhatsApp Cloud API","cerca de R$ 70","Referência para 2.000 mensagens de serviço; marketing é adicional."],["Domínio, logs e segredos","R$ 5 a R$ 15","Custos residuais."],["Total técnico","R$ 225 a R$ 325","Não inclui impostos/IOF, desenvolvimento, suporte ou CRM pago."]],[5.2*cm,3.4*cm,8.8*cm]),Spacer(1,.35*cm),P("Orçamento recomendado: reservar <b>R$ 300 a R$ 350 por mês</b> para infraestrutura e APIs do piloto.","Callout"),P("Itens para aprovação","H2"),grid([["Decisão","Aprovação esperada"],["Escopo","Triagem Comercial e Técnica, com decisão humana obrigatória."],["Tecnologia","Meta Cloud API, Cloud Run, PostgreSQL, OpenAI e integração progressiva com Ploomes."],["Operação","Definir responsáveis Comercial, Técnico, plantão P1/P2, contingência e backups."],["Orçamento","Reservar R$ 300 a R$ 350/mês para o piloto."]],[4.3*cm,13.1*cm]),Spacer(1,.4*cm),P("Responsável Life: ________________________________________________"),P("Data: ____ / ____ / ______     Decisão:  (  ) Aprovar piloto   (  ) Ajustar proposta   (  ) Não aprovar"),Spacer(1,.25*cm),P("Observação: desenvolvimento, implantação, treinamento e suporte são definidos em proposta comercial separada.","Note")]
doc.build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
