from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

OUT = r"output/pdf/Proposta_Atualizada_Piloto_WhatsApp_Life.pdf"
NAVY=colors.HexColor("#183B61"); BLUE=colors.HexColor("#177EAF"); PALE=colors.HexColor("#EDF5F8"); GREY=colors.HexColor("#F4F6F7"); INK=colors.HexColor("#283845"); MUTED=colors.HexColor("#5F7180"); LINE=colors.HexColor("#D4DFE5")
s=getSampleStyleSheet()
s.add(ParagraphStyle(name="CoverK",parent=s["BodyText"],fontName="Helvetica-Bold",fontSize=10,leading=12,textColor=BLUE,alignment=TA_CENTER,spaceAfter=12))
s.add(ParagraphStyle(name="CoverT",parent=s["Title"],fontName="Helvetica-Bold",fontSize=27,leading=32,textColor=NAVY,alignment=TA_CENTER,spaceAfter=12))
s.add(ParagraphStyle(name="Sub",parent=s["BodyText"],fontName="Helvetica",fontSize=12,leading=17,textColor=MUTED,alignment=TA_CENTER))
s.add(ParagraphStyle(name="H1x",parent=s["Heading1"],fontName="Helvetica-Bold",fontSize=18,leading=22,textColor=NAVY,spaceAfter=8))
s.add(ParagraphStyle(name="H2x",parent=s["Heading2"],fontName="Helvetica-Bold",fontSize=11.5,leading=14,textColor=NAVY,spaceBefore=8,spaceAfter=11))
s.add(ParagraphStyle(name="Bodyx",parent=s["BodyText"],fontName="Helvetica",fontSize=9.2,leading=13,textColor=INK,spaceAfter=5))
s.add(ParagraphStyle(name="Cell",parent=s["BodyText"],fontName="Helvetica",fontSize=8.1,leading=10.5,textColor=INK))
s.add(ParagraphStyle(name="Head",parent=s["BodyText"],fontName="Helvetica-Bold",fontSize=8.1,leading=10.2,textColor=colors.white))
s.add(ParagraphStyle(name="BarHead",parent=s["BodyText"],fontName="Helvetica-Bold",fontSize=10.5,leading=12,textColor=colors.white))
s.add(ParagraphStyle(name="Call",parent=s["BodyText"],fontName="Helvetica-Bold",fontSize=10,leading=14,textColor=NAVY,backColor=PALE,borderColor=BLUE,borderWidth=.6,borderPadding=8,borderRadius=4,spaceBefore=4,spaceAfter=8))
s.add(ParagraphStyle(name="Foot",parent=s["BodyText"],fontName="Helvetica",fontSize=7.4,leading=9.4,textColor=MUTED))
def P(t,sty="Bodyx"): return Paragraph(t,s[sty])
def table(rows,widths):
    data=[]
    for ri,row in enumerate(rows): data.append([Paragraph(str(v),s["Head" if ri==0 else "Cell"]) for v in row])
    t=Table(data,colWidths=widths,repeatRows=1,hAlign="LEFT")
    c=[("BACKGROUND",(0,0),(-1,0),NAVY),("GRID",(0,0),(-1,-1),.3,LINE),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)]
    for r in range(2,len(data),2): c.append(("BACKGROUND",(0,r),(-1,r),GREY))
    t.setStyle(TableStyle(c)); return t
def bar(title,text):
    t=Table([[P(title,"BarHead"),P(text)]],colWidths=[4.1*cm,13.1*cm])
    t.setStyle(TableStyle([("BACKGROUND",(0,0),(0,0),BLUE),("BACKGROUND",(1,0),(1,0),PALE),("TEXTCOLOR",(0,0),(0,0),colors.white),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("BOX",(0,0),(-1,-1),.5,BLUE),("LEFTPADDING",(0,0),(-1,-1),8),("RIGHTPADDING",(0,0),(-1,-1),8),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)])); return t
def footer(c,d):
    c.saveState(); c.setStrokeColor(BLUE); c.setLineWidth(2.2); c.line(d.leftMargin,A4[1]-1.02*cm,A4[0]-d.rightMargin,A4[1]-1.02*cm)
    c.setFillColor(NAVY); c.setFont("Helvetica-Bold",8); c.drawString(d.leftMargin,.7*cm,"LIFE ENGENHARIA | Piloto de Atendimento via WhatsApp")
    c.setFillColor(MUTED); c.setFont("Helvetica",8); c.drawRightString(A4[0]-d.rightMargin,.7*cm,f"Página {d.page}"); c.restoreState()
doc=SimpleDocTemplate(OUT,pagesize=A4,leftMargin=1.55*cm,rightMargin=1.55*cm,topMargin=1.6*cm,bottomMargin=1.3*cm,title="Proposta Atualizada - Piloto WhatsApp Life")
st=[]
# cover
st += [Spacer(1,2.4*cm),P("LIFE ENGENHARIA","CoverK"),P("Piloto de Atendimento\nvia WhatsApp","CoverT"),P("Proposta atualizada de escopo, operação, tecnologia e execução","Sub"),Spacer(1,1.25*cm),bar("OBJETIVO","Liberar um piloto controlado para 5 a 10 clientes, com triagem comercial e técnica segura, atendimento humano e operação rastreável."),Spacer(1,.45*cm),P("Direcionamento da proposta","H1x"),P("A automação organiza a demanda, coleta o essencial, gera protocolo e encaminha o atendimento. A decisão comercial, o diagnóstico técnico, a confirmação de urgência e a resposta final continuam sob responsabilidade da equipe da Life."),Spacer(1,.35*cm),table([["Incluído no piloto","Fora desta fase"],["WhatsApp oficial, duas trilhas, Ploomes comercial, fila humana, interface operacional, escalonamento P1/P2 e auditoria.","Dashboard executivo, gráficos avançados, BI, integração com sistema técnico de chamados e automações técnicas."]],[8.6*cm,8.6*cm]),Spacer(1,1.2*cm),P("Documento para validação de escopo, contas, custos, execução e critérios de aceite.","Call"),Spacer(1,2.1*cm),P("Revisão 2 - setembro de 2026","Sub")]
# flow
st += [PageBreak(),P("1. Atendimento e operação humana","H1x"),P("O menu apresentado ao cliente dentro do WhatsApp terá três rotas. A escolha por botões reduz ambiguidade; mensagens livres apenas pedem confirmação antes de iniciar a coleta."),table([["Menu inicial","Destino"],["1. Contratar serviço ou solicitar orçamento","Submenu comercial: limpeza de dutos, PMOC, assistência técnica avulsa, projetos de engenharia, Engenharia Clínica, locação de chillers, chiller novo, Banco de Sangue e outros serviços."],["2. Já sou cliente Life e preciso de assistência técnica","Coleta contrato/histórico Life, equipamento, sintoma, impacto, contingência, risco e anexos seguros."],["3. Falar com uma pessoa","Encaminhamento imediato à fila humana, em qualquer etapa."]],[5.5*cm,11.7*cm]),P("Regras de rota","H2x"),table([["Situação","Tratamento"],["Cliente Life com contrato ou histórico","Pré-triagem, prioridade sugerida P1-P4 e fila técnica humana."],["Solicitação técnica sem contrato","Preserva informações; registra oportunidade de assistência avulsa no Ploomes e encaminha ao Comercial."],["P1/P2","Notifica responsável principal, exige confirmação e escala automaticamente para backup se o SLA não for cumprido."],["E-mail","Recomendado, mas opcional quando o WhatsApp já está confirmado."]],[5.5*cm,11.7*cm]),P("Interface operacional mínima - proposta de tela","H2x"),table([["FILA DE ATENDIMENTOS","DETALHE DO CHAMADO"],["P1  |  Hospital Central  |  aguardando confirmação\nP2  |  Unidade Norte      |  em atendimento\nP3  |  Empresa Alfa       |  novo\n\nFiltros: prioridade | equipe | status | responsável","Protocolo #LIFE-1042  |  P1\nCliente / unidade / equipamento\nResumo da triagem e risco informado\nHistórico de mensagens e anexos\n\nResponsável: ______  Backup: ______\n[ Assumir ]  [ Transferir ]  [ Confirmar ]\n[ Atualizar status ]  [ Registrar ação ]"]],[8.3*cm,8.9*cm]),P("A tela não é um dashboard gerencial. É uma ferramenta de operação para que Comercial, Técnico e plantão controlem a fila, os responsáveis e o contexto de cada caso.","Call")]
# architecture
st += [PageBreak(),P("2. Arquitetura, contas e controles","H1x"),bar("ARQUITETURA","Cliente -> Meta WhatsApp Cloud API -> Backend Fastify no Cloud Run -> Supabase Pro/PostgreSQL -> Ploomes comercial e interface operacional. O cliente recebe retorno sempre pelo canal oficial."),P("Componentes da primeira fase","H2x"),table([["Camada","Decisão","Uso"],["Canal","Meta WhatsApp Cloud API","Messages API e Webhooks para mensagens, anexos e eventos."],["Backend","Node.js, TypeScript e Fastify","Fluxos, protocolos, regras P1-P4, roteamento e escalonamento."],["Hospedagem","Google Cloud Run - São Paulo","Contêiner Docker, HTTPS, mínimo zero e cobrança por uso."],["Banco","Supabase Pro com PostgreSQL","Conversas, protocolos, filas, escalonamentos, anexos e auditoria."],["IA","OpenAI Responses API","Interpretação de texto, extração e resumo; não diagnostica nem decide risco."],["CRM","Ploomes API","Somente leads e oportunidades comerciais nesta fase."],["Segredos","Google Secret Manager","Credenciais fora do código e acesso controlado."]],[3*cm,5*cm,9.2*cm]),P("Propriedade e segurança","H2x"),table([["Tema","Diretriz"],["Propriedade","Meta, Google Cloud, Supabase, GitHub, OpenAI e Ploomes pertencem ou são mantidos sob controle da Life."],["Acessos","Perfis de administrador, comercial, técnico e consulta; menor privilégio, MFA administrativo e trilha de auditoria."],["Ambientes","Homologação e produção isoladas, com dados de teste e credenciais próprias."],["Backup e retenção","Supabase Pro com backup diário e 7 dias incluídos; retenção de conversas/anexos proposta para validação LGPD: 180/90 dias."],["Alertas","Falhas de integração, P1/P2 sem confirmação, indisponibilidade e orçamento de APIs acima do limite."]],[4.5*cm,12.7*cm])]
# execution
st += [PageBreak(),P("3. Plano de execução e aceite","H1x"),P("O cronograma inicia após a Life confirmar os responsáveis, as regras de plantão, os SLAs e a disponibilidade da API do Ploomes."),table([["Etapa","Prazo","Entrega e critério de aceite"],["1. Regras e responsáveis","Semana 1","Menu, perguntas, segmentos, matriz nominal, backups, horários e SLAs aprovados."],["2. Base técnica","Semana 2","Contas Life, ambientes, webhook, banco, segredos, protocolo e auditoria testados."],["3. Fluxos e Ploomes","Semana 3","Rota comercial e assistência avulsa criam/atualizam oportunidade; trilha técnica não usa Ploomes."],["4. Interface operacional","Semana 4","Fila, P1/P2, resumo, anexos, assumir, transferir e status validados pela operação."],["5. Testes e piloto","Semana 5","20 cenários aprovados e liberação para 5-10 clientes selecionados."]],[4*cm,2.2*cm,11*cm]),P("Esforço e responsabilidade","H2x"),table([["Item","Estimativa"],["Esforço técnico","88 a 120 horas, incluindo desenvolvimento, configuração, testes e documentação."],["Custo de desenvolvimento","A definir conforme modalidade e taxa comercial aprovada. Infraestrutura e APIs são contratadas diretamente pela Life."],["Responsáveis Life","Comercial, Coordenação Técnica, Plantão/Backup, Administração/LGPD e administrador Ploomes."],["SLAs propostos","P1 em até 5 minutos e P2 em até 15 minutos, condicionados à definição nominal de cobertura e plantão."]],[5*cm,12.2*cm]),P("Condições de aceite para entrada em piloto","H2x"),table([["Validação obrigatória","Evidência esperada"],["1. Menu e rotas comerciais","Três rotas, segmentos comerciais e regra de assistência avulsa validados."],["2. Operação humana","Fila, responsável, backup, confirmação P1/P2, histórico e anexos testados."],["3. Governança","Contas Life, acessos, alertas, backup e auditoria aprovados."],["4. Liberação controlada","Grupo de 5 a 10 clientes selecionados e cenários de teste concluídos."]],[6.1*cm,11.1*cm]),P("A entrada em piloto ocorrerá somente após as quatro validações acima e a confirmação formal dos responsáveis, backups, horários e cobertura de plantão.","Call")]
# cost
st += [PageBreak(),P("4. Custos recorrentes e dependências","H1x"),P("Referências externas em 25/09/2026. Conversão usada apenas para orçamento: US$ 1 = R$ 5,50. Valores finais variam por câmbio, impostos, consumo e contrato da Life."),table([["Componente","Piloto 5-10 clientes","Projeção 100 clientes"],["Supabase Pro - produção","R$ 137,50","R$ 137,50+"],["Homologação Supabase","R$ 0 a R$ 55,00","R$ 55,00"],["Google Cloud Run","R$ 0 a R$ 15,00","R$ 0 a R$ 40,00"],["OpenAI Responses API","R$ 1 a R$ 5,00","R$ 10 a R$ 30,00"],["Meta WhatsApp Cloud API","R$ 5 a R$ 20,00","R$ 70+"],["GitHub Team - US$ 4/usuário/mês","R$ 66,00 (3 usuários)","R$ 110,00 (5 usuários)"],["Secret Manager e logs","R$ 0 a R$ 10,00","R$ 5 a R$ 20,00"],["Ploomes","A confirmar no plano atual","A confirmar no plano atual"],["Total técnico estimado","R$ 211 a R$ 306/mês","R$ 385 a R$ 500/mês"]],[5.5*cm,5.8*cm,5.9*cm]),P("Ploomes: condição antes da integração","H2x"),P("Antes da etapa 3, a Life deve confirmar a disponibilidade da API no plano atual, criar um usuário de integração e informar qualquer custo adicional. A integração desta fase usa apenas contatos, leads e oportunidades comerciais.","Call"),P("Fontes de referência","H2x"),P("Supabase: plano Pro a US$ 25/mês, backup diário e 7 dias de retenção. Cloud Run: cobrança por uso, região São Paulo disponível. OpenAI: custos por token/modelo. Meta: cobrança por categoria e rate card da conta. GitHub Team: US$ 4 por usuário/mês. Ploomes: disponibilidade e custo dependem do plano Life.","Foot"),Spacer(1,.22*cm),P("Aprovação para prosseguimento","H2x"),bar("DECISÃO","Ao aprovar, a Life autoriza o início da etapa 1 - regras, responsáveis e acessos. Ajustes podem ser registrados abaixo antes da execução."),table([["Responsável Life","Cargo / área","Assinatura ou aceite"],["________________________________","________________________________","________________________________"]],[5.7*cm,5.7*cm,5.8*cm]),P("Data: ____ / ____ / ______     Decisão:   (  ) Aprovar e iniciar etapa 1     (  ) Aprovar com ajustes     (  ) Solicitar revisão","Bodyx"),P("Observações, ajustes ou condicionantes: ____________________________________________________________________________________________","Bodyx")]
doc.build(st,onFirstPage=footer,onLaterPages=footer)
print(OUT)
