export const adminDashboardHtml = `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel do Bot Life</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7f8;color:#16232b;font:16px system-ui,sans-serif}main{max-width:1040px;margin:auto;padding:32px 20px}h1{margin:0 0 8px}.muted{color:#52616a}.login,section{background:#fff;border-radius:12px;padding:24px;box-shadow:0 2px 12px #14212a12}.login{max-width:450px;margin:70px auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(275px,1fr));gap:18px;margin-top:24px}label{display:block;font-weight:600;margin:10px 0 4px}input,select{width:100%;padding:10px;border:1px solid #bdc8cd;border-radius:7px;font:inherit}button{border:0;border-radius:7px;padding:10px 14px;background:#087f5b;color:white;font:inherit;font-weight:700;cursor:pointer;margin-top:16px}button.secondary{background:#52616a;margin-left:8px}.items{margin:14px 0 0;padding:0;list-style:none}.items li{background:#f4f7f8;padding:9px;border-radius:6px;margin-top:6px;display:flex;justify-content:space-between;gap:8px}.items button{margin:0;padding:3px 8px;background:#b42318}.hidden{display:none}.notice{min-height:24px;color:#b42318;margin:12px 0}.ok{color:#087f5b}</style></head><body><main>
<div id="login" class="login"><h1>Painel do Bot</h1><p class="muted">Configuração operacional da Life Engenharia.</p><label>Chave de acesso</label><input id="token" type="password" autocomplete="current-password"><button id="enter">Entrar</button><p id="loginNotice" class="notice"></p></div>
<div id="app" class="hidden"><h1>Configuração operacional</h1><p class="muted">As alterações entram em vigor no bot e ficam registradas na auditoria.</p><p id="notice" class="notice"></p><div class="grid">
<section><h2>Responsáveis</h2><form data-key="responsaveis"><label>Nome<input name="nome" required></label><label>Telefone (com DDI)<input name="telefone" inputmode="numeric" required></label><label>Área<input name="area" required></label><button>Adicionar</button></form><ul class="items" id="responsaveis"></ul></section>
<section><h2>Escalas</h2><form data-key="escalas"><label>Área<input name="area" required></label><label>Dias<input name="dias" placeholder="seg-sex" required></label><label>Início<input name="inicio" type="time" required></label><label>Fim<input name="fim" type="time" required></label><label>Principal<input name="principal" required></label><label>Backup<input name="backup" required></label><button>Adicionar</button></form><ul class="items" id="escalas"></ul></section>
<section><h2>Horários</h2><form data-key="horarios"><label>Área<input name="area" required></label><label>Dias<input name="dias" placeholder="seg-sex" required></label><label>Início<input name="inicio" type="time" required></label><label>Fim<input name="fim" type="time" required></label><button>Adicionar</button></form><ul class="items" id="horarios"></ul></section>
<section><h2>Roteamento</h2><form data-key="roteamento"><label>Solicitação<input name="solicitacao" required></label><label>Destino<input name="destino" required></label><button>Adicionar</button></form><ul class="items" id="roteamento"></ul></section>
</div><button id="logout" class="secondary">Sair</button></div></main><script>
const keys=['responsaveis','escalas','horarios','roteamento'];let settings=[];const auth=()=>({Authorization:'Bearer '+sessionStorage.getItem('adminToken')});const notice=(text,ok=false)=>{const e=document.querySelector('#notice');e.textContent=text;e.className='notice '+(ok?'ok':'')};
function render(){for(const key of keys){const list=document.getElementById(key);list.innerHTML='';settings.filter(s=>s.key===key).forEach((s,index)=>{const li=document.createElement('li');li.append(document.createTextNode(Object.values(s.value).join(' · ')));const remove=document.createElement('button');remove.textContent='Remover';remove.onclick=()=>save(key,settings.filter(x=>x.key!==key||x!==s));li.append(remove);list.append(li)})}}
async function load(){const r=await fetch('/api/admin/settings',{headers:auth()});if(!r.ok)throw Error('Não foi possível carregar as configurações.');settings=await r.json();render()}
async function save(key,next){const values=next.filter(s=>s.key===key).map(s=>s.value);const r=await fetch('/api/admin/settings/'+key,{method:'PUT',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({values})});if(!r.ok)throw Error('Não foi possível salvar.');settings=next;render();notice('Alteração salva e auditada.',true)}
document.querySelectorAll('form').forEach(form=>form.onsubmit=async e=>{e.preventDefault();try{const value=Object.fromEntries(new FormData(form));const key=form.dataset.key;await save(key,[...settings,{key,value}]);form.reset()}catch(err){notice(err.message)}});
document.getElementById('enter').onclick=async()=>{sessionStorage.setItem('adminToken',document.getElementById('token').value);try{await load();document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden')}catch{sessionStorage.removeItem('adminToken');document.getElementById('loginNotice').textContent='Chave inválida ou painel indisponível.'}};
document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('adminToken');location.reload()};if(sessionStorage.getItem('adminToken'))document.getElementById('enter').click();
</script></body></html>`;
